# Generated by Django 5.0.7 on 2024-07-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0003_contactmessage_delete_mymodel_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
