# Generated by Django 5.0.7 on 2024-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0012_project_delete_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
