# Generated by Django 5.0.2 on 2024-08-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0015_events_delete_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
