# Generated by Django 5.0.2 on 2024-08-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0016_rename_events_event_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
