# Generated by Django 5.0.7 on 2024-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0017_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='member',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='member',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='member',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='telephone',
            field=models.CharField(default='0784481603', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
