# Generated by Django 5.0.2 on 2024-07-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioItem',
            new_name='ProjectItem',
        ),
    ]
