# Generated by Django 5.0.2 on 2024-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0002_rename_portfolioitem_projectitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='image',
            field=models.ImageField(height_field='image_height', max_length=255, upload_to='images/%Y/%m/%d/', width_field='image_width'),
        ),
    ]
