# Generated by Django 5.0.2 on 2024-07-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0003_alter_projectitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='image',
        ),
    ]
