# Generated by Django 5.0.2 on 2024-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0005_projectitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='image',
        ),
        migrations.AddField(
            model_name='projectitem',
            name='ProjectImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
