# Generated by Django 5.0.7 on 2024-07-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0006_orderedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('address_3', models.CharField(max_length=100)),
                ('address_4', models.CharField(max_length=100)),
                ('date_of_completion', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ordered_products/')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderedProduct',
        ),
        migrations.AlterField(
            model_name='order',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='photo',
            field=models.ImageField(upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpg_app.order'),
        ),
    ]
