# Generated by Django 5.0.2 on 2024-07-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0006_remove_projectitem_image_projectitem_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='ProjectImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
