# Generated by Django 5.0.7 on 2024-07-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0007_orderproduct_delete_orderedproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='date_of_completion',
        ),
    ]
