# Generated by Django 5.0.2 on 2024-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0008_project_delete_projectitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('width', models.CharField(max_length=10)),
                ('date_published', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
