# Generated by Django 5.0.7 on 2024-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0008_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
