# Generated by Django 5.0.7 on 2024-07-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0008_remove_orderproduct_date_of_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('address_3', models.CharField(max_length=100)),
                ('address_4', models.CharField(max_length=100)),
                ('products', models.CharField(max_length=100)),
                ('sells', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ordered_products/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpg_app.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
