# Generated by Django 5.0.2 on 2024-07-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0009_project_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('width', models.CharField(max_length=10)),
                ('date_published', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Project_Table',
        ),
    ]
