# Generated by Django 5.0.2 on 2024-07-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0009_orderedproduct_delete_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
