# Generated by Django 5.0.2 on 2024-07-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0009_testimonial_delete_testimonials'),
        ('wpg_app', '0011_project_project_table_delete_proj'),
    ]

    operations = [
    ]
