# Generated by Django 5.0.2 on 2024-07-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
