# Generated by Django 5.0.7 on 2024-07-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpg_app', '0013_member_facebook_link_member_instagram_link_and_more'),
        ('wpg_app', '0013_orderedproduct_completed'),
    ]

    operations = [
    ]
